"""monitoring_metrics_and_alerts

Revision ID: 261470096876
Revises: 3c33db8c7f8e
Create Date: 2026-06-07 00:58:26.900409
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '261470096876'
down_revision: str | None = '3c33db8c7f8e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metric', sa.Enum('COST_USD', 'INPUT_TOKENS', 'OUTPUT_TOKENS', 'TOTAL_TOKENS', 'DURATION_MS', 'REQUEST_COUNT', 'ERROR_COUNT', 'ERROR_RATE', 'DENY_COUNT', name='alertmetric', native_enum=False, length=32), nullable=False),
    sa.Column('aggregation', sa.Enum('SUM', 'AVG', 'P50', 'P95', 'P99', 'MAX', 'COUNT', 'RATE', name='alertaggregation', native_enum=False, length=16), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('comparison', sa.Enum('GT', 'GTE', 'LT', 'LTE', name='alertcomparison', native_enum=False, length=8), nullable=False),
    sa.Column('group_by', sa.String(length=32), nullable=True),
    sa.Column('filter_model', sa.String(length=128), nullable=True),
    sa.Column('filter_agent_id', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity', native_enum=False, length=16), nullable=False),
    sa.Column('channel', sa.Enum('SLACK', 'PAGERDUTY', 'WEBHOOK', 'EMAIL', name='alertchannel', native_enum=False, length=16), nullable=False),
    sa.Column('target', sa.String(length=1024), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_events',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.Enum('FIRING', 'RESOLVED', name='alertstate', native_enum=False, length=16), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('group_key', sa.String(length=255), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index('ix_alert_org_fired', ['organization_id', 'fired_at'], unique=False)
        batch_op.create_index('ix_alert_org_state', ['organization_id', 'state'], unique=False)
        batch_op.create_index('ix_alert_rule', ['rule_id'], unique=False)

    op.create_table('metric_events',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('tools_used', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_events_request_id'), ['request_id'], unique=False)
        batch_op.create_index('ix_metric_org_agent', ['organization_id', 'agent_id'], unique=False)
        batch_op.create_index('ix_metric_org_model', ['organization_id', 'model'], unique=False)
        batch_op.create_index('ix_metric_org_project', ['organization_id', 'project_id'], unique=False)
        batch_op.create_index('ix_metric_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index('ix_metric_org_timestamp', ['organization_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_events', schema=None) as batch_op:
        batch_op.drop_index('ix_metric_org_timestamp')
        batch_op.drop_index('ix_metric_org_status')
        batch_op.drop_index('ix_metric_org_project')
        batch_op.drop_index('ix_metric_org_model')
        batch_op.drop_index('ix_metric_org_agent')
        batch_op.drop_index(batch_op.f('ix_metric_events_request_id'))

    op.drop_table('metric_events')
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_rule')
        batch_op.drop_index('ix_alert_org_state')
        batch_op.drop_index('ix_alert_org_fired')

    op.drop_table('alert_events')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
