"""alert_acknowledge_columns

Revision ID: 338fffd05d7a
Revises: 261470096876
Create Date: 2026-06-10 20:27:57.911634
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '338fffd05d7a'
down_revision: str | None = '261470096876'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('acknowledged_by', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_column('acknowledged_by')
        batch_op.drop_column('acknowledged_at')

    # ### end Alembic commands ###
