"""audit_idempotency_constraint

Revision ID: 3c33db8c7f8e
Revises: 11641b201ba4
Create Date: 2026-05-25 23:37:44.454405
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3c33db8c7f8e'
down_revision: str | None = '11641b201ba4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_audit_org_hash', ['organization_id', 'hash'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_constraint('uq_audit_org_hash', type_='unique')

    # ### end Alembic commands ###
